language: go
go: 
 - "1.11.x"

os: osx

install: true

env:
  global:
    - GO111MODULE=on
    - CODECOV_TOKEN="4831691a-c57e-465a-9590-5298c70d066b"

script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)